-- Netherlands has a big deviation in stddev
SELECT STDDEV_POP(SPEED),COUNTRY
FROM SPEEDS,LOCATION
WHERE SPEEDS.LOCID = LOCATION.LOCID
GROUP BY COUNTRY;

-- stddev is massively different between Noordbrabant and Limburg
SELECT STDDEV_POP(SPEED),REGION
FROM SPEEDS,LOCATION
WHERE SPEEDS.LOCID = LOCATION.LOCID
GROUP BY REGION;

-- No difference per city
SELECT STDDEV_POP(SPEED),CITY,REGION
FROM SPEEDS,LOCATION
WHERE SPEEDS.LOCID = LOCATION.LOCID
AND COUNTRY = 'NED'
GROUP BY REGION, CITY
ORDER BY REGION;

-- No diff in stddev per year
SELECT STDDEV_POP(SPEED),AVG(SPEED),COUNTRY,YEAR
FROM SPEEDS,LOCATION,TIMETBL
WHERE SPEEDS.LOCID = LOCATION.LOCID
AND SPEEDS.TIMID = TIMETBL.TIMID
GROUP BY COUNTRY, YEAR
ORDER BY COUNTRY, YEAR;

-- No diff per month
SELECT STDDEV_POP(SPEED),AVG(SPEED),MONTH,REGION
FROM SPEEDS,TIMETBL,LOCATION
WHERE COUNTRY = 'NED'
AND SPEEDS.LOCID = LOCATION.LOCID 
AND SPEEDS.TIMID = TIMETBL.TIMID
GROUP BY REGION, MONTH
ORDER BY REGION, MONTH;

-- No diff per month
SELECT STDDEV_POP(SPEED),AVG(SPEED),MONTH,COUNTRY
FROM SPEEDS,LOCATION,TIMETBL
WHERE SPEEDS.LOCID = LOCATION.LOCID
AND SPEEDS.TIMID = TIMETBL.TIMID
GROUP BY COUNTRY, MONTH
ORDER BY COUNTRY, MONTH;