-- LadaNiva-FSC is slower and is not a supercar
SELECT STDDEV_POP(SPEED), AVG(SPEED), MODEL, CATEGORY
FROM SPEEDS,CAR
WHERE SPEEDS.CARID = CAR.CARID
AND CATEGORY = 'supersport'
GROUP BY CATEGORY, MODEL
ORDER BY CATEGORY;

-- Supersport has higher avg and higher stddev (fewer samples)
SELECT STDDEV_POP(SPEED), AVG(SPEED), CATEGORY
FROM SPEEDS,CAR
WHERE SPEEDS.CARID = CAR.CARID
GROUP BY CATEGORY
ORDER BY CATEGORY;
