-- Ystad has lower avg speed
SELECT STDDEV_POP(SPEED),AVG(SPEED),REGION,CITY
FROM SPEEDS,LOCATION
WHERE SPEEDS.LOCID = LOCATION.LOCID
AND COUNTRY = 'SWE'
GROUP BY REGION,CITY
ORDER BY avg;

-- Ystad has lower avg speed
SELECT STDDEV_POP(SPEED),AVG(SPEED), "month"
FROM SPEEDS
JOIN "location" USING (locid)
JOIN timetbl USING (timid)
WHERE city = 'Ystad'
GROUP BY "month"
ORDER BY avg;

-- stddev higher with Ystad
SELECT STDDEV_POP(SPEED),AVG(SPEED),REGION
FROM SPEEDS,LOCATION
WHERE SPEEDS.LOCID = LOCATION.LOCID
AND COUNTRY = 'SWE'
GROUP BY REGION
ORDER BY REGION;
-- stddev lower without Ystad
SELECT STDDEV_POP(SPEED),AVG(SPEED),REGION
FROM SPEEDS,LOCATION
WHERE SPEEDS.LOCID = LOCATION.LOCID
AND COUNTRY = 'SWE'
AND CITY <> 'Ystad'
GROUP BY REGION
ORDER BY REGION;

-- No difference in regions avg
SELECT STDDEV_POP(SPEED),AVG(SPEED),REGION
FROM SPEEDS,LOCATION
WHERE SPEEDS.LOCID = LOCATION.LOCID
AND COUNTRY = 'SWE'
GROUP BY REGION
ORDER BY REGION;